# Azure DevOps Pipeline for OneView React
# Builds and deploys the React application with Volvo UX/UI to Azure Static Web Apps

trigger:
- main
- develop

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'
  buildConfiguration: 'production'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy OneView React'
  steps:
  - task: NodeTool@0
    displayName: 'Setup Node.js $(nodeVersion)'
    inputs:
      versionSpec: '$(nodeVersion)'
  
  - script: |
      echo "Node.js version: $(node --version)"
      echo "NPM version: $(npm --version)"
    displayName: 'Display Environment Info'
  
  - script: npm ci
    displayName: 'Install Dependencies'
  
  - script: npm run build
    displayName: 'Build Application'
  
  - script: |
      if [ -f "web.config" ]; then cp web.config dist/; fi
      if [ -f "staticwebapp.config.json" ]; then cp staticwebapp.config.json dist/; fi
      if [ -d "api" ]; then cp -r api dist/; fi
      echo "Build completed successfully"
      ls -la dist/
    displayName: 'Copy Configuration Files'
  
  - task: ArchiveFiles@2
    displayName: 'Archive Build Artifacts'
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/oneview-react-$(Build.BuildId).zip'
      replaceExistingArchive: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'oneview-react-build'
