# OneView React - Azure Pipeline
# Simple and reliable configuration

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'

steps:
- task: NodeTool@0
  displayName: 'Use Node.js $(nodeVersion)'
  inputs:
    versionSpec: '$(nodeVersion)'

- script: |
    echo "Starting OneView React build..."
    echo "Node.js version: $(node --version)"
    echo "NPM version: $(npm --version)"
  displayName: 'Environment Info'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React application'

- script: |
    echo "Build completed successfully"
    echo "Contents of dist folder:"
    ls -la dist/
  displayName: 'Verify build output'

- task: ArchiveFiles@2
  displayName: 'Archive build artifacts'
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/oneview-react.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'oneview-build'
