# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: "Build and deploy Node.js app to Azure Web App - OneView-VFSLATAM"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Building React frontend..."
          npm run build:frontend
          echo "Verifying dist folder was created..."
          ls -la dist/
          if [ ! -f "dist/index.html" ]; then
            echo "ERROR: dist/index.html was not created!"
            exit 1
          fi
          echo "✅ Frontend build successful"
          echo "Installing API dependencies..."
          cd api && npm install && cd ..
          echo "✅ Build process completed successfully"

      - name: Create deployment package
        run: |
          echo "Creating deployment package..."
          mkdir -p deployment-package
          
          # Copy built React frontend
          if [ -d "dist" ]; then
            echo "✅ Copying dist/ folder..."
            cp -r dist/ deployment-package/
          else
            echo "❌ ERROR: dist/ folder not found!"
            exit 1
          fi
          
          # Copy API files
          if [ -d "api" ]; then
            echo "✅ Copying api/ folder..."
            cp -r api/ deployment-package/
          else
            echo "❌ ERROR: api/ folder not found!"
            exit 1
          fi
          
          # Copy configuration files
          echo "✅ Copying configuration files..."
          cp package.json deployment-package/
          cp web.config deployment-package/
          cp server.js deployment-package/
          
          echo "✅ Deployment package created successfully"
          echo "Package contents:"
          ls -la deployment-package/
          
      - name: Zip artifact for deployment
        run: |
          cd deployment-package
          zip -r ../release.zip . -x "*.DS_Store" "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OneView-VFSLATAM'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SECRETNAME }}
